# O que é acessibilidade?

## Definição de acessibilidade urbana

Acessibilidade é a facilidade com que as pessoas conseguem alcançar lugares e oportunidades – ou, inversamente, uma característica de lugares e oportunidades em termos do quão facilmente eles podem ser alcançados pela população [@geurs2004accessibility; @neutens2010equity].

As condições de acessibilidade são influenciadas tanto pela co-distribuição espacial da população e de atividades econômicas e de serviços públicos quanto pela configuração e desempenho da rede de transportes. Nesse sentido, a acessibilidade urbana tem papel fundamental na capacidade das pessoas de se deslocarem para acessar oportunidades, como empregos, escolas, *etc*.

Os níveis de acessibilidade urbana são estabelecidos, portanto, por três componentes distintos:

- **Infraestrutura**: A facilidade de acessar atividades depende da infraestrutura e dos serviços de transporte existentes. Isso inclui, por exemplo, a capilaridade da rede de transporte público, a conectividade da rede viária, a existência de corredores de transporte de alta capacidade, como trens e metrôs, etc. Aqui, tanto a eficiência quanto a conectividade espacial e temporal da rede de transportes são de extrema importância.

- **Uso do solo**: O quão facilmente atividades podem ser acessadas também depende da co-distribuição espacial de pessoas e atividades, como escolas, serviços de saúde, áreas de lazer, *etc*. Esse componente diz respeito à proximidade geográfica entre pessoas e oportunidades: quanto mais longe, mais difícil é o acesso às atividades.

- **Pessoas**: Por fim, é importante ressaltar que a facilidade de acessar atividades também é afetada pelas características individuais de cada pessoa. Fatores como dificuldades motoras e cognitivas, idade, gênero, cor e renda, por exemplo, podem influenciar de maneira importante a capacidade das pessoas de se locomoverem, de utilizarem determinados modos de transporte e de circularem pela cidade sem medo de algum tipo de violência ou descriminação.

Este último componente traz importantes informações para análises de equidade e inclusão social. No entanto, a sua influência sobre as condições de acessibilidade das pessoas costuma ser melhor captada em análises qualitativas: por conta de dificuldades operacionais e computacionais, essa dimensão da acessibilidade costuma receber pouca atenção de avaliações de impacto de projetos de transporte de larga escala. No [Capítulo 2](2_indicadores.qmd), discutimos mais a fundo as vantagens e desvantagens operacionais, teóricas e de comunicação de diferentes indicadores de acessibilidade.

## Diferença entre microacessibilidade e acessibilidade urbana

Para fins de esclarecimento de conceitos, é importante distinguir entre o que chamamos de acessibilidade urbana e o que em geral se entende por acessibilidade, em português.

O termo *acessibilidade* é comumente utilizado para se referir a questões de padrões e normas de *design* universal e de construção e planejamento para inclusão de pessoas com diferentes graus de dificuldades motoras e cognitivas. Isso é o que normalmente entende-se por **microacessibilidade**, pois abrange questões de acesso a serviços e atividades na escala micro - ou seja, tratando de como características do planejamento de espaços públicos e privados, e a construção de veículos, por exemplo, afetam a capacidade de cada indivíduo de conseguir acessar lugares, serviços, produtos, *etc*.

A *acessibilidade urbana*, por sua vez, pode ser entendida como **macroacessibilidade**, pois trata de questões de acesso de uma maneira mais ampla: quando falamos de acessibilidade urbana, nos concentramos em como questões estruturais de planejamento e desenvolvimento urbano, como a disposição de corredores de transportes e a distribuição espacial de pessoas e atividades, afetam a capacidade das pessoas de acessar oportunidades. Ela trata de como a capacidade de acessar atividades é influenciada tanto pelas capacidades das pessoas utilizarem tecnologias de transporte quanto pela co-distribuição espacial de pessoas e atividades e pela cobertura e conectividade da rede de transporte.

Notadamente, a microacessibilidade e a macroacessibilidade são elementos complementares de uma noção mais ampla de acessibilidade. Condições de microacessibilidade, por exemplo, afetam diretamente a capacidade de pessoas embarcarem e utilizarem diferentes modos de transporte, de se locomoverem com segurança sobre calçadas, de atravessarem ruas, *etc*. De pouco adianta um indivíduo morar em uma região atendida por uma grande oferta de modos de transporte se ele tem dificuldades de locomoção, por exemplo, e a rede de transporte não é adaptada para essas dificuldades. Neste livro, focaremos apenas em análises de acessibilidade urbana e muitas vezes utilizaremos o termo acessibilidade como um sinônimo de macroacessibilidade por uma questão de fluência do texto. É importante reconhecer, no entanto, que a macroacessibilidade de forma isolada não é suficiente para descrever as condições de acessibilidade de um indivíduo em sua totalidade, e que para tal precisamos olhar também para a microacessibilidade.

## Por que a acessibilidade urbana importa?

O conceito de acessibilidade é central em estudos de transporte por diferentes razões. Primeiramente, este conceito articula de maneira explícita como políticas de transporte e de desenvolvimento e uso do solo urbano interagem e impactam a capacidade das pessoas acessarem as oportunidades nas cidades. Por sua vez, o acesso a oportunidades e atividades, como postos de trabalho e serviços de educação e de saúde, por exemplo, tem papel fundamental para a satisfação das necessidades individuais e sociais da população e para promoção da inclusão social [@pereira2021transportation, @luz2022understanding]. Boas condições de acessibilidade também são condição necessária, embora não suficiente, para a expansão da liberdade de escolha das pessoas [@church2000transport; @lucas2016transport; @vanwee2022accessibility]. O conceito de acessibilidade, portanto, serve como fio condutor para relacionar investimentos e políticas de transportes e uso do solo a questões relacionadas à exclusão social e à qualidade de vida de indivíduos, como o potencial de satisfação de necessidades básicas e a liberdade.

Adicionalmente, a ideia de acessibilidade traz à tona a dimensão espacial de um problema central de justiça social: a desigualdade de oportunidades. Ela ajuda a incorporar de maneira explícita a noção de espaço no desenho de políticas destinadas a enfrentar essas injustiças [@farrington2005rural; @pereira2017distributive]. Assim, a noção de acessibilidade é peça fundamental para pensar a equidade de políticas públicas e para avaliar os aspectos distributivos de quais grupos sociais e quais localidades se beneficiam dessas políticas. 

Como vimos anteriormente, os níveis de acesso a oportunidades em uma cidade são resultado conjunto da capacidade de cada pessoa utilizar tecnologias de transporte, da integração entre a distribuição geográfica das atividades e a distribuição espacial da população na cidade e da conectividade espacial e temporal da rede de transportes [@miller2018accessibility; @paez2012measuring]. O planejamento com foco na acessibilidade, desta forma, passa por um planejamento integrado entre o uso do solo e o sistema de transportes, buscando aproximar pessoas e atividades e reduzir a dependência de modos de transporte motorizados [@banister2011trilogy]. Planejar as cidades e sistemas de transporte visando melhorar as condições de acessibilidade, portanto, é essencial para o desenvolvimento de cidades inclusivas e sustentáveis.

## Diferença entre acessibilidade e mobilidade

É importante esclarecer a diferença entre a acessibilidade e outro conceito muito presente em nosso dia-a-dia: a mobilidade. Infelizmente, a diferença entre esses conceitos é frequentemente ignorada, mesmo por pesquisadores e planejadores que lidam com esses temas diariamente. Afinal de contas, existe uma grande intersecção temática entre a acessibilidade e o que se entende por "mobilidade urbana" enquanto área de pesquisa e política pública: uma área que lida com os deslocamentos das pessoas, que está relacionada ao planejamento de sistemas de transporte coletivo e individual, com o planejamento de redes cicloviárias e de pedestres, *etc*. Neste contexto, não é raro, por exemplo, ouvir que um determinado grupo "tem menos mobilidade" do que outro, quando na verdade o correto seria dizer que esse grupo apresenta piores condições de acessibilidade. Qual é, então, a diferença entre acessibilidade e mobilidade?

Na literatura científica e de planejamento urbano e de transportes, o conceito de mobilidade diz respeito aos padrões de viagens que as pessoas efetivamente fazem no seu dia-a-dia – por exemplo, quantas viagens foram feitas, quais modos de transporte foram usados, qual a distância média das viagens, quanto tempo se gasta no deslocamento casa-trabalho, *etc*. Informações de mobilidade são tradicionalmente captadas por meio de pesquisas domiciliares origem-destino. Recentemente, com o surgimento de novas tecnologias digitais, dados de GPS de telefones celulares, de cartões de bilhetagem eletrônica, de radares e semáforos urbanos, entre outros, vêm também sendo usados com a finalidade de descrever os deslocamentos diários da população [@anda2017transport; @kandt2021smart]. Dados e análises de mobilidade trazem informações sobre o uso do sistema de transportes e sobre os padrões de viagens de indivíduos de diferentes grupos socioeconômicos, o que nos permite captar importantes aspectos do desempenho econômico e ambiental das cidades e do bem-estar da população.

O conceito de acessibilidade, por sua vez, está intrinsecamente relacionado ao *potencial* que as pessoas têm de alcançar atividades e oportunidades. Enquanto uma análise de mobilidade foca, por exemplo, no tempo que as pessoas levam diariamente de sua casa ao seu trabalho, uma análise de acessibilidade tenta identificar, por exemplo, a quantidade de empregos que podem ser alcançados dentro de um determinado custo de viagem, ou se as pessoas conseguiriam alcançar serviços públicos em um tempo de viagem tido como razoável. A acessibilidade trata do quão fácil/factível é alcançar um local, enquanto a mobilidade trata dos meios de deslocamento efetivamente utilizados para chegar até ele. Níveis de acessibilidade são, portanto, medidas potenciais, ao passo que os dados de mobilidade descrevem padrões reais, realizados.

Tradicionalmente, o planejamento urbano e de transportes tem como foco a mobilidade [@banister2011trilogy, @vasconcellos2018urban, @levinson2020transport]. Ainda hoje, o foco na mobilidade motiva políticas que priorizam a circulação de automóveis e visam aumentar a velocidade e a fluidez de trânsito para reduzir congestionamentos e, consequentemente, reduzir tempos de deslocamento [levine2019mobility]. Essas políticas, no entanto, tendem a dar um enfoque quantitativo na mobilidade: aumentar o número de viagens, aumentar a velocidade média, diminuir o tempo de congestionamento, *etc*. Neste contexto, portanto, a mobilidade é vista como um fim em si mesma, e "melhorar" a mobilidade depende de políticas com soluções puramente técnicas que devem "otimizar" os aspectos quantitativos mencionados anteriormente. 

A mobilidade, no entanto, não pode ser encarada como uma finalidade em si. As pessoas raramente se deslocam pelo simples prazer de se deslocar. Ao contrário, na grande maioria das vezes as pessoas se deslocam como um meio para acessar as atividades localizadas no destino da viagem. Neste sentido, tem-se observado um crescente consenso entre pesquisadores e agências de transporte de que o objetivo de uma política de transportes é melhorar o acesso da população a bens e oportunidades [@pereira2017distributive; @martens2012justice; @bertolini2005sustainable]. Se o que as pessoas querem é acessar atividades, precisamos pensar em formas de planejamento que resultem em políticas que facilitem seu acesso a tais atividades - sem necessariamente promover a motorização e o aumento da velocidade no trânsito, que implicam no aumento de externalidades econômicas, ambientais, de saúde pública, entre outras.

O que observamos, portanto, é uma mudança de paradigma no planejamento urbano e de transportes: a busca por padrões de viagem mais sustentáveis implica na mudança do foco da mobilidade para a acessibilidade [@banister2008sustainable; cervero2005accessible; levine2019mobility]. Políticas de aumento de velocidade nas vias e de expansão de faixas, por exemplo, podem ser substituídas por políticas de promoção de maior *mix* de uso do solo e de aproximação de pessoas e atividades, promovendo maior integração entre planejamento de transportes e de uso do solo. Dessa forma, a mudança de foco da mobilidade para a acessibilidade urbana, abre um leque maior de possíveis instrumentos e ações de políticas públicas que buscam promover um desenvolvimento urbano mais integrado e calcado na promoção da sustentabilidade e da inclusão social [@banister2011trilogy; levine2019mobility].
