# What is accessibility?

## Definition of urban accessibility

Accessibility is the ease with which people can reach places and opportunities – or, conversely, a characteristic of places and opportunities in terms of how easily they can be achieved by the population [@geurs2004accessibility; @neutens2010equity].

Accessibility conditions are influenced both by the spatial co-distribution of the population, economic activities and public services, as well as by the configuration and performance of the transport network. In this sense, urban accessibility has a fundamental role in shaping people's ability to move in order to access opportunities, such as jobs, schools, *etc*.

Urban accessibility levels are determined by three distinct components:
- **Infrastructure**: the ease of access to activities depends on existing infrastructure and transportation services. This includes, for example, the spatial coverage and connectivity of the public transport and road networks, the existence of high-capacity transport services such as trains and subways, etc. Here, both the efficiency and spatial and temporal connectivity of the transport network are of utmost importance.

- **Land use**: how easily activities can be accessed also depends on the spatial co-distribution of people and activities such as schools, health services, leisure areas, etc. This component concerns the geographical proximity between people and opportunities: the further away an activity is, the more difficult it is to access it.

- **People**: finally, it is important to note that the ease of accessing activities is also affected by individuals' personal characteristics. Factors such as motor and cognitive difficulties, age, gender, race, and income, for example, can significantly influence people's ability to get around, use certain modes of transportation, and move around the city without fear of some kind of violence or discrimination.

This last component can be of critical importance for analyzes concerned with equity and social inclusion. However, the influence of people's personal characteristics on accessibility conditions is usually better through qualitative analyses. Due to operational and computational difficulties, this dimension of accessibility usually receives little attention from impact assessments of large-scale transportation projects. In [Capítulo 2](2_indicadores.en.qmd), we discuss more in depth the operational, theoretical, and communication advantages and disadvantages of different accessibility drivers.


## Difference between micro-accessibility and urban accessibility

For the purpose of clarifying concepts, it is important to distinguish between what we call urban accessibility and what is the colloquial use of the term accessibility.


The term *accessibility* is commonly used to refer to issues universal design standards and regulations, as well as construction and planning practices aimed at the inclusion of people with different degrees of motor and cognitive difficulties. This is what is usually meant by **micro-accessibility**, because it covers issues of access to services and activities at the micro scale. In other words, it relates to how the planning of public and private spaces, and the construction of vehicles, for example, affect the ability of individuals to be able to access places, services, products, etc.
*Urban accessibility*, in turn, can be understood as **macro-accessibility**, because it deals with a broader understanding of access. When we talk about urban access, we focus on how structural issues of planning and urban development, such as the configuration of transport corridors and the spatial distribution of people and activities, affect people's ability to access opportunities. Urban accessibility addresses how the ability to access activities is influenced by people's ability to use transportation technologies, the spatial co-distribution of people and activities, and the spatial coverage and connectivity of transportation networks.
Micro-accessibility and macro-accessibility are complementary elements of a broader notion of accessibility. Micro-accessibility conditions, for example, directly affect the ability of people to board and use different modes of transport, to move safely on sidewalks, to cross streets, etc. It is of little use for a person to live in a region served by various modes of transport if, for example, she has limited mobility and the transport network and vehicles are not adapted to these difficulties. In this book, we will focus only on analyses of urban accessibility and will often use the term accessibility as a synonym of macro-accessibility. It is important to recognize, however, that macro-accessibility in isolation provides only a limited account of one’s accessibility conditions, and a more nuanced understanding of accessibility requires a closer look at micro-accessibility conditions as well.

## Why does urban accessibility matter?

The concept of accessibility is central in transport and planning studies for different reasons. First, this concept explicitly articulates how the interaction between transport, urban development and land use policies impact people's ability to access opportunities in cities. Moreover, access to opportunities and activities, such as jobs, education, and health services plays a fundamental role for the satisfaction of individual and social needs and promotion of social inclusion [@pereira2021transportation; @luz2022understanding]. Good accessibility is also a necessary condition, although not sufficient, for the expansion of people's freedom of choice [@church2000transport; @lucas2016transport; @vanwee2022accessibility]. The concept of accessibility helps us understand how transport and land use investments can have implications for issues related to social exclusion and wellbeing, such as the satisfaction of basic needs, freedom, and equity.

Additionally, the idea of accessibility brings to the forefront the spatial dimension of inequality of opportunities, which is a central problem of social justice. Urban accessibility helps to explicitly incorporate the notion of space into policy design to address these injustices [@farrington2005rural; @pereira2017distributive]. Thus, the notion of accessibility is fundamental for thinking about the equity implications of public policies and evaluating the distributive aspects of which social groups and which localities benefit from these policies.

As mentioned before, the levels of access to opportunities in a city are a joint result of each person's ability to use transportation technologies, the spatial co-distribution of activities and population in the city, and the spatial and temporal connectivity of the transport network  [@miller2018accessibility; @paez2012measuring]. As such, an accessibility-oriented planning seeks to promote the integration between land use and the transport systems, increasing the proximity between people and activities and reducing the dependence on motorized modes of transport [@banister2011trilogy]. Planning cities and transport systems to improve accessibility conditions is therefore essential for the promotion of more inclusive and sustainable cities.

## Difference between accessibility and mobility

It is important to clarify the difference between accessibility and another concept very present in our daily life: mobility. Unfortunately, the difference between these concepts is often ignored, even by researchers and planners who deal with these topics on a daily basis. After all, there is a great intersection between accessibility and what is meant by "urban mobility" as a broad field of research and public policy, and which deals with people's daily mobility patterns, and the planning of public and individual transport systems, including the planning of cycling and pedestrian networks. In this context, it is not uncommon, for example, to hear that a given socioeconomic group "has less mobility" than another, when in fact one wants to say that this group has worse accessibility conditions. So, what is the difference between accessibility and mobility?

In the scientific literature on urban and transport planning, the concept of mobility refers to people’s daily travel behavior patterns – for example, the number of trips conducted, what transport modes are used, the average distance of trips or how much time people spent commuting to work. Information on mobility patterns is commonly collected through household travel surveys. More recently, new approaches such as GPS sensors from mobile phones and smart cards have also been increasingly used to examine daily mobility patterns [@anda2017transport; @kandt2021smart]. Mobility data and analyses provide information about the travel patterns of different socioeconomic groups and how transport systems are used, which reflect important aspects of the economic and environmental performance of cities and population well-being.

The concept of accessibility, in turn, refers to the *potential* capability of reaching activities and opportunities. While a mobility analysis would focus, for example, on the time people spend on their daily commute to work, an accessibility analysis would examine, for example, the quantity and variety of jobs one could potentially reach within a reasonable travel cost. Accessibility addresses how easy/feasible it is to reach a location, while mobility deals with the means of movement used to reach a location. Accessibility levels are therefore potential measures, while mobility data describe real, observed travel behavior.

Traditionally, urban and transport planning focuses on mobility [@banister2011trilogy; @vasconcellos2018urban; @levinson2020transport]. Even today, the focus on mobility motivates policies to prioritize the movement of cars, and to increase the speed and flow of traffic as a means to tackle congestion and reduce travel times [@levine2019mobility]. These policies, however, tend to focus on mobility metrics: increasing the number of trips, increasing the average speed, decreasing congestion, etc. From this perspective, mobility is seen as an end in itself, and the solutions to "improve" mobility would depend purely on technical solutions that "optimize" traffic speed and flow.

Mobility, however, cannot be seen as an end in itself. As a rule, people do not travel for the simple pleasure of traveling around. On the contrary, most of the time people travel as a means to access the activities or people they want to engage with. In this sense, there is a growing consensus among researchers and transportation agencies that the goal of a transport policy is to improve people’s access to opportunities [@pereira2017distributive; @martens2012justice; @bertolini2005sustainable]. If what people want is to access activities, we need to rethink how urban, land use and transport planning practices could be redesigned to improve accessibility - without necessarily increasing traffic speeds or the dependence on motorized vehicles, which are known to cause negative economic, environmental, and public health externalities.

There is a call for a paradigm shift in urban and transport planning where the pursuit for more sustainable travel patterns requires changing the focus from mobility to accessibility [@banister2008sustainable; @cervero2005accessible; @levine2019mobility]. Policies that seek to increase traffic speed and road capacity, for example, could be replaced by policies that promote proximity between people and activities through greater land use mix or the integration between transport and land use planning. Thus, the shift from mobility to accessibility opens up a wider range of possible public policy instruments and actions to promote a more integrated urban development based on principles of sustainability and social inclusion [@banister2011trilogy; @levine2019mobility].

