# Accessibility measures

Promoting a paradigm shift in urban and transport planning towards accessibility-oriented planning entails a few challenges. Among them, there is the need to develop and apply methods to measure the urban accessibility conditions in cities. In the search for accessibility metrics that are easy to communicate, methodologically robust, and computationally tractable, researchers have developed a large number of different measures [@paez2012measuring]. These measures can be divided into two major groups: place-based measures and person-based measures [@dijst2002opportunities].

## Place-based measures

Place-based metrics measure accessibility as a characteristic of a particular location. By simplification, these indicators assume that all people who are in the same place can equally access the activities distributed throughout the city. That is, if an accessibility analysis uses a place-based metric to calculate accessibility and divides the study area into a grid, each cell of that grid (a square) will have an accessibility value associated with it and which is equally assigned to all individuals residing within each cell. These measures are sensitive to land use and transport factors related to the spatial distribution of activities and to the configuration and performance of the transport network, but do not take into account individuals’ personal characteristics.

These measures are the most widely used by transport agencies and researchers [@boisjoly2017how; @papa2015accessibility]. This is largely because they require less data and tend to be considerably easier to calculate and interpret than people-based accessibility measures. For this reason, the examples and case studies presented in this and the next chapters of the book focus only on place-based measures of accessibility.

Place-based accessibility measures account for trip costs, usually expressed in terms of travel time [@el-geneidy2016cost; @venter2016assessing] - i.e., if one location can be reached from another in half an hour, the cost to make this trip is 30 minutes. However, it is possible to consider other types of costs, such as the distance of the trip, its monetary cost, and the perception of comfort of users [@arbex2020estimating; @herszenhut2022impact]. We present below some of the place-based accessibility metrics most commonly used in the scientific literature and by transport agencies. Here, the term "cost" is used broadly, and can refer to any type of cost unit used to quantify the impedance of a trip, be it travel time, monetary cost, or other alternatives.

### Minimum travel cost

One of the simplest accessibility metrics is the minimum travel cost measure. It indicates the lowest cost required to reach the nearest opportunity from a given origin. It allows one to estimate, for example, the travel time to the health center closest to each block of a city. The indicator is calculated with the following formula:

$$A_i = min(c_{i1}, c_{i2}, \dots, c_{ij}, \dots, c_{i(n-1)}, c_{in}) \iff O_j \geq 1$$

where $A_i$ is the accessibility at origin $i$, $c_{ij}$ is the travel cost between origin $i$ and destination $j$, $n$ is the total number of destinations in the study area, and $O_j$ is the number of opportunities at destination $j$.

**Advantages and disadvantages:** The advantages of this measure are that it requires little data, and it is easy to calculate and to communicate. Two disadvantages, however, are that it does consider the quantity of accessible opportunities at destinations, nor does it take into account aspects of competition in demand for opportunities. For example, even if a person lives very close to a hospital, this proximity does not necessarily guarantee good access to health services if this is the only hospital in the region and is subject to demand peaks that overload the services beyond their capacities.

### Cumulative opportunity measures

The cumulative opportunity accessibility metric measures the number of opportunities that can be reached within a given travel cost limit. For example, this indicator can be used to measure the number of jobs accessible by public transport in up to 60 minutes, or the number of schools accessible within 30 minutes of walking. The measure is calculated using the following formula:

$$A_i = \sum_{j=1}^{n}{O_j \times f(c_{ij})}$$

$$
f(c_{ij}) =
  \begin{cases}
	1 & \text{se } c_{ij} \leq C\\
	0 & \text{otherwise}
  \end{cases}
$$
 
where $A_i$ is accessibility at origin $i$, $O_j$ is the number of opportunities at destination $j$, $n$ is the total number of destinations in the study area, $f(c_{ij})$ is a binary function that assumes the values 0 or 1, depending on the travel cost of $c_{ij}$ between origin $i$ and destination $j$, and $C$ is a max travel cost threshold.

**Advantages and disadvantages:** The cumulative opportunities measure also requires little data, and it is easy to calculate and communicate. This helps explain why this is one of the indicators most commonly used by transport and funding agencies in accessibility analyses [@papa2015accessibility; @boisjoly2017how]. Among its disadvantages are the fact that this indicator does not consider the competition for opportunities and that it requires the choice of a single cut-off point as a travel cost limit. Moreover, this measure assumes that all opportunities that can be reached within the pre-established travel cost limit are equally desirable and accessible. For example, if we consider a 60-minute travel time limit, an opportunity that is 40 minutes aways from an origin is considered as accessible as another one that is just 10 minutes away.

### Gravity measures

More than a specific type of accessibility metric, we can understand gravity-based accessibility as a family of measures. As in the case of the cumulative opportunity measure, gravity-based metrics considers the sum of opportunities that can be reached from a given location. However, the number of opportunities in each destination is gradually discounted as travel costs become higher. In other words, opportunities that are easier to access are considered to be more valuable, and the weight of each opportunity decreases as it gets more difficult to reach it from the trip origin.
The rate at which the weight of each opportunity decreases is determined by travel costs and is determined by a **decay function** that can be specified in various ways. For example, the **linear** decay function considers that the weight of each opportunity decreases linearly up to a certain cost limit, after which the weight becomes zero. The **negative exponential** function, on the other hand, considers that the weight of each opportunity is divided by a factor that grows exponentially, causing the weight to decrease rapidly at low travel costs and to approach 0 at high costs. The equations below present the generic formulation of a gravitational measure as well as the linear and negative exponential decay functions mentioned above.

$$A_i = \sum_{j=1}^{n}{O_j \times f(c_{ij})}$$

$$
f_{lin}(c_{ij}) =
  \begin{cases}
	1-c_{ij}/C & \text{se } c_{ij} \leq C\\
	0 & \text{otherwise}
  \end{cases}
$$

$$f_{exp}(c_{ij}) = e^{-\beta c_{ij}}$$

where $A_i$ is the accessibility at origin $i$, $O_j$ is the number of opportunities at destination $j$, $n$ is the total number of destinations in the study area, $f(c_{ij})$ is a decay function whose result varies with the travel cost $c_{ij}$ between origin $i$ and destination $j$, $f_{lin}(c_{ij})$ is the linear decay function, $C$ is travel cost limit, $f_{exp}(c_{ij})$ is the negative exponential decay function, and $\beta$ is a parameter that dictates the decay speed.

There are numerous types of decay functions that can be used in the calculation of gravity-based accessibility measures. The cumulative opportunities measure, for example, can be understood as a special case of a gravity-based measure in which the weight of each opportunity is dictated by a binary function, rather than a function that decays gradually. @levinson2020transport [p. 49] present a list of decay functions often used by transport agencies and researchers in analyses involving gravity accessibility.

**Advantages and disadvantages:** The main advantage of gravity-based accessibility measures is that, by discounting the weight of opportunities by the travel cost to reach them, these measures reflect to some extent how people perceive access to opportunities: services and activities that are closer to them tend to be perceived as more valuable, all else equal. This indicator, however, has at least two disadvantages. The first is that the estimated accessibility levels are difficult to interpret because of the way in which the number of opportunities is discounted by travel costs. Additionally, the decay rate of the impedance function (the $\beta$ parameter of the negative exponential function, for example) needs to be calibrated if one wants the accessibility estimates to be representative of people's travel behavior. Therefore, gravity-based metrics require additional travel behavior data or other types of data (such as household travel surveys or mobile phone data) that can be used in the calibration process.


### Accessibility measures with competition: *floating catchment area*

In many cases, access to opportunities is affected not only by geographical proximity and transportation costs, but also by the competition of many people trying to access the same opportunity. This is very common, for example, in the cases of access to health services, schools, and jobs. A job opening can only be occupied by one person at a time, and the same goes for an intensive care unit (ICU) bed or a school seat.
There are various measures that seek to account for competition in accessibility estimates. Some of the most widely used accessibility measures with competition are those in the *floating catchment area* (FCA) family of indicators. For example, these indicators try to take into account how the same person can potentially access multiple ICU beds and, simultaneously, that each ICU bed can potentially be accessed by multiple people. Thus, a person's access to ICU beds is influenced by issues of transportation costs but also by the availability of beds given the potential competing demand for them.
Within the FCA family of measures, the most commonly used is the 2-Step Floating Catchment Area (2SFCA), originally proposed by @luo2003measures. One limitation of 2SFCA is that it considers that the same person can demand multiple services / opportunities at the same time and that the same service can be used by multiple people at the same time. These issues are known as the demand and supply inflation problems, respectively, and can generate biased or inaccurate accessibility estimates [@paez2019demand]. To deal with these problems, @paez2019demand proposed the Balanced Floating Catchment Area (BFCA), one of the most recent measures of the FCA family.

**Advantages and disadvantages:** Different FCA measures have different advantages and disadvantages, to a greater or lesser extent. However, in general, the main advantage of measures of this family is its ability to incorporate aspects of competition into accessibility estimates. The main disadvantage, on the other hand, is the difficulty interpreting and communicating its results.

## Medidas baseadas em pessoas

People-based accessibility measures are sensitive not only to the spatial distribution of activities and to the configuration and performance of transportation networks. Indicators in this group also take into account how the personal characteristics of each individual (such as gender, age, physical disability, etc.), and even the participation in certain in activities and personal commitments, can affect their capability to access opportunities. This category includes, for example, activity-based indicators [@dong2006moving] and space-time measures [@kim2003spacetime, @neutens2012analysis].

**Advantages and disadvantages:** Although people-based accessibility measures are more sophisticated, they often require large amounts of data, such as people’s travel diary records, household travel surveys, etc. Therefore, the calculation of these measures is computationally more intensive, which makes them less frequently used than place-based measures [@neutens2010equity, @miller2018accessibility]. In contrast to place-based measures, which give a single accessibility estimate for all individuals in the same place, people-based measures give one accessibility estimate per person because they take into account the particularities of each individual. While this allows for more nuanced accessibility analyses, this also makes the communication of people-based accessibility results more complex.

