#  Comparando a acessibilidade entre dois cenários de transporte

Neste capítulo nós avaliaremos o impacto de uma política relativamente simples, mas que pode trazer significativos benefícios em termos de acessibilidade à população: o aumento da frequência das linhas de transporte público.

Para isso, nós precisaremos comparar os níveis de acessibilidade antes e depois da suposta implementação desta política. Precisamos, portanto, modificar o GTFS original da área de estudo para atualizar as frequências das rotas nele descritas, calcular duas matrizes de tempo de viagem distintas (uma antes e outra depois da política), calcular dois conjuntos de níveis de acessibilidade distintos e comparar esse conjunto. Neste capítulo, vamos cobrir este passo-a-passo em detalhes, começando primeiro pela edição do GTFS original.

## Modificação do arquivo GTFS

fdsafsda

## Cálculo da acessibilidade nos cenários antes e depois

FDSAFSAD

## Visualização dos níveis e da diferença de acessibilidade

FSADFSD

## Distribuição da acessibilidade entre grupos sociais

FASDFSDA