# PARTE 1: Introdução a acessibilidade urbana

<div style="text-align: justify">


**Objetivo**: O objetivo desse capítulo é (1) apresentar o que o conceito de acessibilidade urbana e esclarecer a diferença entre acessibilidade e mobilidade; e (2) apresentar uma visão geral sobre os principais indicadores para se medir acessibilidade.


Quantos postos de trabalho se consegue acessar em menos de uma hora usando transporte público? Quanto tempo se leva para chegar até o posto de saúde ou escola mais próxima da sua casa? As respostas a essas perguntas dependem diretamente das políticas de transporte e de desenvolvimento urbano das cidades. Essas políticas determinam em larga medida a acessibilidade urbana, isto é, a facilidade com a qual pessoas de diferentes grupos sociais e níveis de renda distintos conseguem acessar oportunidades de emprego, serviços de saúde e educação, atividades culturais e de lazer. Assim, essas políticas têm papel-chave para o funcionamento da economia, para a construção de cidades mais sustentáveis e inclusivas e para a redução da desigualdade de acesso a oportunidades

</div>
