# SECTION 1: Introduction to urban accessibility

**The objectives of this section** are (1) to introduce the concept of urban accessibility, clarifying the difference between accessibility and mobility, and (2) to present an overview of the main measures used to estimate accessibility levels.

How many jobs can a person in a given location reach within an hour of travel using public transport? How long does it take for this person to get to the health center or the school closest to her home? The answers to these questions depend directly on local transport and urban development policies. These policies shape the urban accessibility conditions in each city - that is, the ease with which each individual can access employment opportunities, health and education services, and cultural and leisure activities, among other types of activities. Accessibility is, therefore, the combined result of the connectivity and performance of transport systems and the spatial organization of cities in terms of the distribution of population, economic activities and public services. Promoting the adoption of this concept in urban and transport planning can lead to higher rates of economic development and help promote more sustainable and inclusive cities. Throughout this section, we will study the concept of urban accessibility in more details, looking at why it is important to understand how cities work and what measures are most commonly used to estimate accessibility levels.
