# SEÇÃO 1: Introdução à acessibilidade urbana

**Objetivo:** Os objetivos desta seção são (1) apresentar o conceito de acessibilidade urbana, esclarecendo a diferença entre acessibilidade e mobilidade, e (2) apresentar uma visão geral dos principais indicadores usados para medir níveis de acessibilidade.

Quantos postos de trabalho uma pessoa em um determinado local consegue alcançar em até uma hora de viagem usando transporte público? Quanto tempo essa pessoa leva para chegar até o posto de saúde ou a escola mais próxima de sua casa? As respostas a essas perguntas dependem diretamente das políticas locais de transporte e de desenvolvimento urbano. Essas políticas determinam os níveis de acessibilidade urbana em cada cidade - isto é, a facilidade com que cada indivíduo consegue acessar oportunidades de emprego, serviços de saúde e educação, atividades culturais e de lazer, entre outros tipos de atividade. A acessibilidade, portanto, é simultaneamente um resultado da conectividade e performance dos sistemas de transporte e da organização espacial das cidades em termos da distribuição da população, de atividades econômicas e de serviços públicos em seus territórios. Promover o uso deste conceito no planejamento urbano e de transportes pode levar a maiores índices de desenvolvimento econômico e ajudar a promover cidades mais sustentáveis e inclusivas. Ao longo desta seção, vamos entender com mais detalhes o conceito de acessibilidade urbana, por que ele é importante para entendermos o funcionamento das cidades e quais os indicadores mais comumente utilizados para medir os níveis de acessibilidade.

