# SEÇÃO 3: Dados de transporte público

**Os objetivos desta seção** são (1) apresentar a especificação GTFS de dados de transporte público, (2) mostrar onde baixar dados GTFS de cidades brasileiras e do mundo, e (3) apresentar exemplos de como analisar e manipular dados de GTFS usando R.

Dados de transporte público são peças fundamentais no planejamento de transportes em geral, e em análises de acessibilidade em particular. Para serem usados de forma que se tenha segurança no resultado das análises, esses dados precisam ser confiáveis e de simples inspeção e interpretação.

Tentando satisfazer esses critérios, cada vez mais agências de transporte público, tomadores de decisão e pesquisadores têm buscado utilizar dados estruturados conforme especificações abertas e colaborativas - ou seja, cujo formato seja decidido por uma comunidade de atores interessados, incluindo partes que produzem esses dados (agências de transporte público, por exemplo) e que os consomem (pesquisadores, desenvolvedores de ferramentas de planejamento, *etc*). Embora uma especificação aberta não necessariamente resolva o problema da qualidade e da confiabilidade dos dados por ela descritos, ela traz várias vantagens que promovem o compartilhamento de conhecimento e a transparência de análises e aplicações que dependem dessa especificação - fatores que, por sua vez, podem levar a substanciais ganhos de qualidade e confiança nos dados.

O uso de um formato padrão de dados para transporte público permite o desenvolvimento e compartilhamento de ferramentas e programas computacionais para análise desses dados, o que cria um campo comum de compartilhamento e aprendizado entre atores de diferentes cidades e países. Assim, um programa desenvolvido por uma agência de transporte no Brasil, pode ser facilmente utilizado por um pesquisador nos Estados Unidos, por um desenvolvedor no Japão ou por outra agência de transporte na África do Sul - desde que, é claro, eles também organizem seus dados no mesmo formato. Além disso, quanto mais amplamente utilizado é esse formato, maior tende a ser tanto a confiabilidade na especificação em si quanto à facilidade de inspeção e à interpretação dos seus dados, visto que múltiplos atores detêm o conhecimento necessário para isso.

A especificação de dados aberta e colaborativa mais amplamente utilizada no contexto do planejamento de transporte público é o formato GTFS, sigla para *General Transit Feed Specification* (Especificação Geral de Redes de Transporte Público, em tradução livre). Seus usos abrangem tanto o planejamento quanto a operação de sistemas de transporte público. Como visto no [Capítulo 3](3_calculando_acesso.qmd), os dados de GTFS também são uma peça fundamental para calcular estimativas de acessibilidade urbana por transporte público. Nesta seção, iremos aprender em mais detalhes o que são os dados GTFS, como eles são estruturados e como trabalhar com esses dados em R.