# SECTION 4: Impact assessment of transportation projects

**The purpose of this section** is to present a step-by-step example of how one can use the methods presented in this book to assess the impact of a transport infrastructure project on urban accessibility using R.

Although accessibility analyses have been frequently used in scientific literature for more than two decades, only recently transport agencies and decision makers have begun to pay more attention to urban accessibility issues in their day-to-day planning and in the operation of transport systems [@papa2015accessibility; @boisjoly2017how]. Much of this is due to the difficulty of incorporating accessibility analyses to project evaluation methods and planning activities [@silva2017accessibility; @buttner2021accessibility]. 

In this section, we use a subway expansion project in Fortaleza (Brazil) as a case study to illustrate how to use the methods and R packages presented in the previous chapters to assess the accessibility impacts of transport infrastructure projects. The [Chapter 6](6_cenarios_transporte.en.qmd) presents a method for evaluating the effect of transportation investments not only on the overall accessibility level of the population, but also for examining how this effect is distributed geographically and among different socioeconomic groups, ultimately impacting disparities in access to opportunities. The application of the method involves the use and manipulation of different GTFS files, the calculation of travel time matrices, the decision-making behind the choice of which accessibility measure to use, the estimation of accessibility levels, the spatial visualization of these estimates and the calculation and analysis of inequality indicators. Therefore, this case study covers numerous topics discussed in the book and serves as a practical example of the concepts presented thus far.

It is important to mention that the evaluation of transportation projects, investments or policies should ideally encompass a wide range of criteria. These criteria range from aspects of social participation in policy and project formulation to their environmental, economic and social impacts. While an evaluation of accessibility impact is very important for characterizing the potential benefits and performance of a transport network, it offers a limited perspective of the effects of a given policy. Evaluations of this type should therefore complement and be accompanied by other analyses that investigate the other impacts that a transportation project might have.
