# O que é acessibilidade?

## Definição de acessibilidade urbana

Acessibilidade é a facilidade com que as pessoas conseguem alcançar lugares e oportunidades – ou, inversamente, uma característica de lugares e oportunidades em termos de quão facilmente eles podem ser alcançados pela população (Geurs & van Wee, 2004; Neutens et al., 2010). 


A noção de acessibilidade está relacionada tanto à co-distribuição espacial da população e de atividades econômicas e serviços públicos quanto à configuração e desempenho das redes de transporte. Nesse sentido, a acessibilidade urbana tem papel fundamental na capacidade das pessoas de se deslocarem para acessar oportunidades (como empregos, escolas, etc.).


tres componentes:

\- Infraestrutura

\- Uso do solo

\- Pessoas

O nível de acessibilidade de uma cidade ou bairro depende da eficiência e conectividade da rede de transporte, mas também da proximidade entre pessoas e atividades. A promoção de cidades mais sustentáveis, inclusivas e inteligentes exige políticas que melhorem a acessibilidade urbana e reduzam as desigualdades de acesso a oportunidades.


## Por que acessibilidade importa?

O conceito de acessibilidade é central em estudos de transporte por várias razões. Esse conceito articula de maneira mais explícita como políticas de transporte e políticas de desenvolvimento e uso do solo urbano interagem de maneira a impactar as capacidades das pessoas de se deslocarem nas cidades. O acesso a postos trabalho, serviços de educação e saúde tem papel fundamental para a satisfação das necessidades individuais e sociais, e é uma condição necessária, embora não suficiente, para a expansão da liberdade de escolha das pessoas (Church, Frost e Sullivan, 2000; Farrington, 2007; Lucas et al., 2016). Ademais, a ideia de acessibilidade traz à tona a dimensão espacial da injustiça e desigualdade no acesso a oportunidades, e ajuda a incorporar de maneira explícita a noção de espaço no desenho de políticas destinadas a enfrentar essas injustiças (Farrington e Farrington, 2005; Pereira, Schwanen e Banister, 2017).

O nível de acesso a oportunidades numa cidade é um resultado conjunto da capacidade de as pessoas utilizarem tecnologias de transporte e da integração entre a distribuição geográfica de atividades vis-à-vis a conectividade espacial e temporal da rede de transporte (Miller, 2018; Páez, Scott e Morency, 2012). Assim, a construção de cidades mais inclusivas e sustentáveis passa, em larga medida, por um planejamento integrado entre uso do solo e do sistema de transporte, o que tende a criar maior proximidade entre pessoas e atividades, aumentando a acessibilidade urbana e reduzindo a dependência de modos de transporte motorizados (Banister, 2011)


## Diferença entre micro e macro acessibilidade



Para fins de esclarecimento de conceitos, é importante distinguir entre o que nós chamamos de acessibilidade urbana e o uso mais corrente que é feito no português da palavra acessibilidade.

- O termo *acessibilidade* é comumente utilizado para se referir a questões relacionadas à normas de design, construção e planejamento para inclusão de pessoas com diferentes graus e tipos de deficiência física. Isso é o que nós podemos chamar de **microacessibilidade**, pois trata na escala micro individual da capacidade de pessoas conseguirem acessar lugares, serviços, produtos etc.
- A expressão *acessibibilidade urbana*, por sua vez, pode ser entendida como **macroacessibilidade**, poist trata de uma maneira mais ampla sobre como a capacidade das pessoas de acessarem atividades considerando tanto as as capacidades das pessoas utilizarem tecnologias de transporte quanto a  distribuição espacial de atividades vis-à-vis a cobertura e conectividade da rede de transporte. 


Note, portanto, que microacessibilidade é um importante componente de uma noção mais ampla de acessibilidade urbana. Ainda, ambas micro e macroacessibilidade tem papel fundamental em moldar a mobilidade urbana da população.


## Diferença entre acessibilidade e mobilidade urbana

A noção de acessibilidade é diferente, mas complementar à de mobilidade urbana. Estudos sobre mobilidade urbana costumam olhar para os padrões de viagens que as pessoas efetivamente fazem no seu dia a dia – por exemplo, quantas viagens foram feitas, que modo de transporte as pessoas usam, qual o tempo de deslocamento casa-trabalho etc. Essas questões são tipicamente captadas por meio de pesquisas origem-destino, e trazem importantes informações sobre as condições de transporte e bem-estar das pessoas.

No entanto, a mobilidade não é um fim em si mesma. As pessoas se deslocam como um meio para acessar as atividades no destino da viagem, incluindo oportunidades de emprego, lazer, serviços, entre outras. O enfoque na acessibilidade urbana destaca justamente essa atividades e oportunidades que podem ser acessadas pelas pessoas, dadas as suas características individuais, a forma de organização espacial das cidades e a maneira como se organizam os sistemas de transporte.

