# Indicadores de acessibilidade

Existem diversos indicadores para se medir acessibilidade. Esses indicadores podem ser divididos em dois grandes grupos: indicadores baseados em lugar e indicadores baeados em pessoas
[@dijst2002opportunities].

## Medidas baseadas em lugares

 Medidas baseadas em lugar medem a acessibilidade enquanto uma característica de um determinado local. Por simplificação, esses indicadores assumem que todas as pessoas que se encontram em um mesmo local tem as mesmas condições de acesso às atividades distribuídas pela cidade. Esses indicadores são sensíveis a fatores relacionados a distribuição espacial de atividades e a configuração e desempenho da rede de transporte, mas não levam em consideração as características individuais das pessoas. 

Os indicadores desse tipo os mais amplamente utilizados por agências de transporte e pesquisadores (ref). Isso porque esses indicadores exigem menor quantidade de dados e são consideravelmente mais fáceis de serem calculados.Por este motivo, todo o material desse curso irá se focar nesses indicadores de acessibilidade basedos em lugares. 

Nós apresentamos abaixo uma rápida descrição de alguns desses indicadores.

### Mínima distância ou tempo de viagem

### Medida cumulativa de oportunidades

### Medidas gravitacionais

### Indicadores com competição: Floating catchment area


## Medidas baseadas em pessoas

Indicadores de acessibilidade baseadas em pessoas são sensíveis não apenas à distribuição espacial de atividades e a configuração e desempenho da rede de transporte. Esses indicadores mas também levam em consideração como características pessoais (como sexo, idade, deficiência física etc) e até questões como atividades e compromissos pessoais podem afetar a facidade de uma pessoa acessar determinadas atividades. Esse grupo de medidas inclui, por exemplo, indicadores de acessibilidade baseados em utilidade ou medidas de espaço-tempo.

Os indicadores desse tipo costumam demanda grande quantidades de dados, incluindo registros de diários de viagem, pesquisas domiciliares tipo origem-destino etc. Além disso, o cálculo desses indicadores é computacionalmente mais intensivo e complexo, o que faz com que esses indicadores sejam menos utilizados, embora mais sofisticados (ref).