# PARTE 2: Dados do Projeto AOP

**Objetivo**: o objetivo deste capítulo é mostrar como você pode usar o `R` para fazer download dos dados do projeto Acesso a Oportunidades (AOP) utilizando o pacote `aopdata`.

Esses dados permitem você analisar diversas estimativas de de acessibilidade a empregos e serviços públicos, como escolas, estabelecimentos de saúde e centros de referência para assistência social (CRAS). Essas estimativas são calculadas usando vários indicadores de acessibilidade, considerando diferentes modos de transporte (caminhada, bicicleta, transporte público e automóvel), diferentes horários do dia (pico e fora-pico) e diferentes grupos populacionais (segundo níveis de renda, rara, sexo e idade).

Nesta versão, a base de dados traz essas informações para os anos de 2017, 2018 e 2019, se apoiando em uma única metodologia consistente para as 20 maiores cidades do Brasil. As metodologias utilizadas para gerar estes dados são apresentadas em detalhe em publicações separadas, para os dados populacionais e de uso do solo (ref), e para os dados de acessibilidade (ref).




